---
  - name: create volumes fact
    set_fact:
      vol:
        device_name: '/dev/{{ item.attach_point }}'
        volume_type: 'gp2'
        volume_size: "{{ item.volume_size }}"
        delete_on_termination: 'true'
    with_items: "{{vols}}"
    register: volumes

  - name: Provision EC2 Box
    local_action:
      module: ec2
      profile: "{{ aws_profile }}"
      region: "{{ region }}"
      key_name: "{{ ec2_keypair }}"
      group: "{{ aws_security_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      vpc_subnet_id: "{{ ec2_subnet_ids}}"
      instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
      assign_public_ip: "{{ public_ip}}"
      count: "{{ number_of_instances }}"
      termination_protection: "{{ termination_protection }}"
      wait: true
      volumes: "{{ volumes.results | map(attribute='ansible_facts.vol') | list }}"
    register: ec2